log_level: INFO
log_path: logs/app.log
group_prefix: "grp_"
schema_creation_group: "Professores"
databases:
  - name: "local"
    host: "localhost"
    dbname: "postgres"
    user: "postgres"
    port: 5432
