connect_timeout: 5
databases:
- dbname: GeoIFSC
  host: 172.16.0.228
  name: Novo
  port: 5432
  user: postgres
group_prefix: grp_
log_level: DEBUG
log_path: D:\GitHub\IFSC_SGBD\logs\app.log
schema_creation_group: Professores
user_prefix: ''
