connect_timeout: 5
databases:
- dbname: Campus_Mauro_Ramos_db
  host: 172.16.0.228
  name: remoto
  port: 5432
  user: postgres
- dbname: Campus_Mauro_Ramos_db
  host: 172.16.0.228
  name: Geral
  port: 5432
  user: postgres
group_prefix: grp_
log_level: DEBUG
log_path: D:\GitHub\IFSC_SGBD\logs\app.log
schema_creation_group: Professores
