log_level: INFO
log_path: logs/app.log
group_prefix: "grp_"
schema_creation_group: "Professores"
databases:
  - name: "local"
    host: "localhost"
    dbname: "postgres"
    user: "postgres"
    password: "postgres"
    port: 5432
  - name: "remoto"
    host: "db.example.com"
    dbname: "producao"
    user: "admin"
    password: "s3cr3t"
    port: 5432
